-- Create freezer_inventory table
create table if not exists freezer_inventory (
  id serial primary key,
  user_telegram_id text, -- keeping for compatibility with existing schema if needed
  item_name text not null,
  quantity numeric not null,
  unit text not null, -- 'servings', 'portions', 'pieces', 'cubes', 'packages'
  category text, -- 'Prepared Components', 'Proteins', 'Vegetables', etc.
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create recipe_usage_log table
create table if not exists recipe_usage_log (
  id serial primary key,
  user_telegram_id text,
  recipe_id bigint references notes(id),
  freezer_item_name text,
  quantity_used numeric,
  date_used timestamp with time zone default now()
);

-- Insert initial freezer inventory data
insert into freezer_inventory (item_name, quantity, unit, category) values
  ('Sliced Marinated Chicken', 20, 'servings', 'Prepared Components'),
  ('Curry Paste Cubes', 15, 'cubes', 'Prepared Components'),
  ('Stuffed Shells', 11, 'portions', 'Prepared Components'),
  ('Ground Beef Portions', 12, 'portions', 'Proteins'),
  ('Whole Chicken Breasts', 20, 'pieces', 'Proteins'),
  ('Hot Italian Sausage', 3, 'packages', 'Proteins')
on conflict do nothing;

-- Create notes table (used for recipes)
create table if not exists notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users default auth.uid(),
  title text,
  content text,
  note_type text default 'note', -- 'recipe', 'grocery_list', etc.
  metadata jsonb default '{}'::jsonb, -- flexible storage for recipe details, ingredients, etc.
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Enable Row Level Security (RLS)
alter table notes enable row level security;

-- Create policies (allow public read for now since auth isn't fully implemented, but restrictive write)
create policy "Public notes are viewable by everyone."
  on notes for select
  using ( true );

create policy "Users can insert their own notes."
  on notes for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own notes."
  on notes for update
  using ( auth.uid() = user_id );

-- Insert sample recipes
insert into notes (title, content, note_type, metadata) values
  ('Spaghetti Carbonara', 'Cook pasta. Fry bacon. Mix eggs and cheese. Combine.', 'recipe', '{"image_url": "https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=800", "rating": 5, "tried_status": true, "dietary_tags": ["Contains Pork", "High Carb"]}'),
  ('Vegetable Stir Fry', 'Chop veggies. Stir fry in wok with soy sauce.', 'recipe', '{"image_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800", "rating": 4, "tried_status": false, "dietary_tags": ["Vegan", "Healthy"]}'),
  ('Grilled Chicken Salad', 'Grill chicken. Toss with greens and vinaigrette.', 'recipe', '{"image_url": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800", "rating": 0, "tried_status": false, "dietary_tags": ["High Protein", "Low Carb"]}')
on conflict do nothing;
